language: python
python:
 - "2.7"
 - "2.6"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"

addons:
  apt:
    packages:
        gettext  # This was removed in the Precise release on

matrix:
  allow_failures:
    python: "3.6-dev"

install:
    - pip install --upgrade pip
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - pip install coveralls coverage

script: coverage run --include=bagit.py setup.py test

after_success:
    coveralls
